#ifndef LAMBDA_PLUGIN_GLOBAL_H
#define LAMBDA_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LAMBDA_PLUGIN_LIBRARY)
#  define LAMBDA_PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LAMBDA_PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LAMBDA_PLUGIN_GLOBAL_H
